export const AFRICAN_COUNTRIES = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Congo",
  "Côte d'Ivoire",
  "Democratic Republic of the Congo",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
] as const;

export const BUSINESS_SECTORS = [
  "Agriculture & Agribusiness",
  "Banking & Finance",
  "Construction & Real Estate",
  "Education",
  "Energy & Utilities",
  "Healthcare & Pharmaceuticals",
  "Hospitality & Tourism",
  "Information Technology",
  "Legal & Consulting",
  "Logistics & Transport",
  "Manufacturing",
  "Media & Communications",
  "Mining & Natural Resources",
  "Retail & Consumer Goods",
  "Telecommunications",
  "Trade & Import-Export",
  "Other",
] as const;
